window.WB = {
 esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},
 block(b,state={answers:{},checks:{},notes:{}}){if(LearningGames.types[b.type])return LearningGames.html(b,state.answers?.[b.id]);const e=this.esc, a=state.answers?.[b.id];let out=`<div class="block"><h3>${e(b.title||'')}</h3><p class="preview-text">${e(b.text)}</p>`;
 if(b.type==='image')out+=`<img class="workbook-image" src="${e(b.image)}" alt="${e(b.text)}" style="max-width:${Math.max(20,Math.min(100,Number(b.width)||100))}%">`;
 if(b.type==='video')out+=b.videoMode==='inline'?`<div class="video-player"><video controls preload="metadata" playsinline src="${e(b.url)}" aria-label="${e(b.title||b.text||'Учебное видео')}"></video><a href="${e(b.url)}" target="_blank" rel="noopener noreferrer">Если видео не воспроизводится — открыть отдельно ↗</a></div>`:`<a class="video-card" href="${e(b.url)}" target="_blank" rel="noopener noreferrer" aria-label="Смотреть видео: ${e(b.title||b.text)}"><span class="video-play" aria-hidden="true"><svg viewBox="0 0 24 24" width="34" height="34"><path d="M8 5v14l11-7z" fill="currentColor"/></svg></span><span><small>ВИДЕОМАТЕРИАЛ</small><strong>${e(b.title||b.text||'Учебное видео')}</strong><span>Смотреть видео ↗</span></span></a>`;
 if(b.type==='link')out+=`<a href="${e(b.url)}" target="_blank" rel="noopener noreferrer">Открыть инструкцию ↗</a> ${b.download?`<a class="button" href="${e(b.download)}" target="_blank" rel="noopener noreferrer">Скачать</a>`:''}`;
 if(['single','multiple','boolean'].includes(b.type))out+=b.options.map((o,i)=>`<label><input type="${b.type==='multiple'?'checkbox':'radio'}" name="${b.id}" data-answer="${b.id}" value="${i}" ${(a||[]).includes(i)?'checked':''}>${e(o)}</label>`).join('');
 if(['open','notes'].includes(b.type))out+=`<textarea rows="${Math.max(2,Math.min(20,Number(b.rows)||4))}" data-${b.type==='open'?'open':'note'}="${b.id}">${e(b.type==='open'?a:state.notes?.[b.id])}</textarea>${b.type==='open'?'<small>Ответ просматривает преподаватель. Автоматические баллы не начисляются.</small>':''}`;
 if(b.type==='practice')out+=`<label><input type="checkbox" data-check="${b.id}" ${state.checks?.[b.id]?'checked':''}>Задание выполнено</label><label>Скриншоты выполненного задания ${b.evidenceRequired?'(обязательно)':'(по желанию)'} · до ${b.maxImages||3}</label>${ScreenshotInput.html(b.id)}<div class="evidence-gallery" data-gallery="${b.id}"></div>`;
 return out+'</div>'},
 content(c,state){return `<h1>${this.esc(c.title)}</h1><p class="preview-text">${this.esc(c.description)}</p>`+c.sections.map((s,i)=>`<section class="card" id="section-${i}"><h2>${i+1}. ${this.esc(s.title)}</h2>${s.blocks.map(b=>this.block(b,state)).join('')}<label><input type="checkbox" data-done="${i}" ${state?.done?.[i]?'checked':''}>Раздел изучен</label></section>`).join('')}
};
