(function(){
"use strict";
const source=window.WORKBOOK_COURSES&&window.WORKBOOK_COURSES[document.body.dataset.course];
if(!source){document.body.innerHTML="<h1>Курс не найден</h1>";return;}
const course={...source,modules:source.modules.map(m=>({...m,short:m.title.replace(/^(День|Блок)\s+\d+\s*/u,""),concepts:m.concepts.map(x=>({title:x.title,text:x.text})),materials:m.materials.split(";").map(x=>x.trim()).filter(Boolean),quiz:m.quiz.map(x=>({text:x.q,options:x.o,correct:x.a,explanation:x.e}))}))};
const key=`ifcm-workbook-v2-${course.id}`,sessionKey="ifcm-workbook-session",apiBase=String(window.WORKBOOK_API_URL||"").replace(/\/$/,"");
let auth=readSession(),state=loadLocal(),saveTimer=null,syncTimer=null;
function empty(){return{checks:{},answers:{},notes:{},done:{},profile:{name:"",unit:""}}}
function loadLocal(){try{return Object.assign(empty(),JSON.parse(localStorage.getItem(key)||"{}"))}catch(e){return empty()}}
function readSession(){try{return JSON.parse(sessionStorage.getItem(sessionKey)||"null")}catch(e){return null}}
function writeSession(value){auth=value;if(value)sessionStorage.setItem(sessionKey,JSON.stringify(value));else sessionStorage.removeItem(sessionKey)}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function stats(){let totalChecks=0,checked=0,totalQ=0,answered=0,correct=0;course.modules.forEach((m,mi)=>{totalChecks+=m.practice.length;m.practice.forEach((_,pi)=>{if(state.checks[`${mi}-${pi}`])checked++});m.quiz.forEach((q,qi)=>{totalQ++;const a=state.answers[`${mi}-${qi}`];if(a!==undefined){answered++;if(Number(a)===q.correct)correct++}})});const percent=Math.round(((checked+answered)/(totalChecks+totalQ))*100)||0;return{totalChecks,checked,totalQ,answered,correct,percent,points:correct*10}}
async function api(path,options={}){if(!apiBase)throw new Error("Сервис сохранения ещё не подключён");const headers={"Content-Type":"application/json",...(options.headers||{})};if(auth&&auth.token)headers.Authorization=`Bearer ${auth.token}`;const response=await fetch(`${apiBase}${path}`,{...options,headers});let data={};try{data=await response.json()}catch(e){}if(!response.ok){const error=new Error(data.detail||"Не удалось выполнить запрос");error.status=response.status;throw error}return data}
function notify(message,isError=false){let box=document.getElementById("syncState");if(!box){box=document.createElement("div");box.id="syncState";box.className="sync-state";document.body.appendChild(box)}box.textContent=message;box.classList.toggle("error",isError);box.classList.add("show");clearTimeout(syncTimer);syncTimer=setTimeout(()=>box.classList.remove("show"),2600)}
function save(){localStorage.setItem(key,JSON.stringify(state));update();clearTimeout(saveTimer);if(auth&&auth.token)saveTimer=setTimeout(saveRemote,700)}
async function saveRemote(){try{await api(`/api/v1/progress/${course.id}`,{method:"PUT",body:JSON.stringify({state,summary:stats()})});notify("Результат сохранён на сервере")}catch(error){if(error.status===401){writeSession(null);renderLogin("Сеанс завершён. Войдите повторно");return}notify("Нет связи с сервером. Изменения сохранены на этом устройстве",true)}}
function renderLogin(message=""){document.body.innerHTML=`<main class="login-page"><section class="login-brand"><img src="../assets/ifcm-logo.svg" alt="iFCM GROUP"><div><small>Интерактивная рабочая тетрадь</small><h1>${esc(course.title)}</h1><p>Введите ФИО и код, полученный у преподавателя. Прогресс будет сохранён и доступен при следующем входе.</p></div></section><section class="login-panel"><form class="login-card" id="loginForm"><div class="block-label">Доступ к обучению</div><h2>Вход в рабочую тетрадь</h2><p>Корпоративная учётная запись не требуется.</p><label for="fullName">Фамилия и имя</label><input id="fullName" name="fullName" autocomplete="name" maxlength="160" required placeholder="Например, Иванова Мария"><label for="accessCode">Код доступа</label><input id="accessCode" name="accessCode" type="password" autocomplete="one-time-code" maxlength="200" required placeholder="Введите код курса"><button class="login-submit" type="submit">Открыть тетрадь</button><div class="login-error ${message?"show":""}" id="loginError">${esc(message)}</div><p class="login-privacy">ФИО и результаты обучения сохраняются на сервере курса.</p></form></section></main>`;document.getElementById("loginForm").addEventListener("submit",login)}
async function login(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector("button"),error=document.getElementById("loginError");button.disabled=true;button.textContent="Проверяем…";error.classList.remove("show");try{const result=await api("/api/v1/session",{method:"POST",body:JSON.stringify({full_name:form.fullName.value.trim(),code:form.accessCode.value,course_id:course.id})});writeSession(result);await openWorkbook()}catch(e){error.textContent=e.message;error.classList.add("show");button.disabled=false;button.textContent="Открыть тетрадь"}}
async function openWorkbook(){try{const remote=await api(`/api/v1/progress/${course.id}`);if(remote.state)state=Object.assign(empty(),remote.state)}catch(error){if(error.status===401){writeSession(null);renderLogin("Сеанс завершён. Войдите повторно");return}}shell();wire();update();show(location.hash.slice(1)||"start")}
function nav(){return course.modules.map((m,i)=>`<a class="nav-link" href="#m${i+1}" data-nav="m${i+1}"><span class="nav-num">${i+1}</span><span>${esc(m.short)}</span><span class="nav-state"></span></a>`).join("")}
function shell(){document.body.innerHTML=`<header class="topbar"><a class="top-brand" href="index.html"><img src="../assets/ifcm-logo.svg" alt="iFCM GROUP"><span>Рабочая тетрадь</span></a><div class="top-course">${esc(course.short)}</div><div class="top-progress"><div class="progress-rail"><i id="rail"></i></div><span class="score" id="topScore">0</span></div><span class="user-chip">${esc(auth&&auth.full_name||"")}</span><button class="top-button" id="logout">Выйти</button><button class="top-button" id="print">Печать</button></header><aside class="sidebar"><a class="side-home" href="#start" data-nav="start"><b>•</b><span>Начало</span></a><div class="nav-group"><div class="nav-group-title">Программа курса</div>${nav()}</div><div class="nav-group"><div class="nav-group-title">Результат</div><a class="nav-link" href="#final" data-nav="final"><span class="nav-num">★</span><span>Итоги и памятка</span><span class="nav-state"></span></a></div><div class="side-foot"><button id="export">Сохранить результаты</button><button id="reset">Начать заново</button></div></aside><main class="main">${intro()}${course.modules.map(moduleHtml).join("")}${finalHtml()}</main><div class="sync-state" id="syncState"></div>`}
function hero(num,kicker,title,lead){return `<div class="hero"><div class="hero-num">${num}</div><div class="hero-kicker">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(lead)}</p></div>`}
function intro(){return `<section class="screen" id="start">${hero("•",`Интерактивный курс · ${course.duration}`,course.title,course.intro)}<div class="content"><div class="outcome"><small>Как работать</small><b>Изучите опорный материал, выполните действия в тестовой базе, отметьте чек‑лист и ответьте на контрольные вопросы.</b></div><h2>Правила учебной работы</h2><div class="theory-grid">${course.rules.map((x,i)=>`<article class="theory-card"><b>0${i+1}</b><p>${esc(x)}</p></article>`).join("")}</div><div class="pager"><span></span><button class="next" data-go="m1">Начать обучение →</button></div></div></section>`}
function moduleHtml(m,mi){const id=`m${mi+1}`,next=mi===course.modules.length-1?"final":`m${mi+2}`;return `<section class="screen" id="${id}">${hero(mi+1,`Модуль ${mi+1} · ${m.minutes}`,m.title,m.outcome)}<div class="content"><div class="outcome"><small>Результат модуля</small><b>${esc(m.outcome)}</b></div><h2>Опорный материал</h2><div class="theory-grid">${m.concepts.map(c=>`<article class="theory-card"><b>${esc(c.title)}</b><p>${esc(c.text)}</p></article>`).join("")}</div>${materialsHtml(m,mi)}<section class="practice"><div class="block-label">Практика · тестовая база</div><h2>Выполните по шагам</h2><div class="check-list">${m.practice.map((x,pi)=>{const k=`${mi}-${pi}`;return `<label class="check"><input type="checkbox" data-check="${k}" ${state.checks[k]?"checked":""}><span>${esc(x)}</span></label>`}).join("")}</div><label class="note-label" for="note-${mi}">${esc(m.prompt)}</label><textarea class="note" id="note-${mi}" data-note="${mi}" placeholder="Запишите вывод или вопрос преподавателю…">${esc(state.notes[mi]||"")}</textarea></section>${quizHtml(m,mi)}<label class="module-done"><input type="checkbox" data-done="${mi}" ${state.done[mi]?"checked":""}> Материал разобран, практическое задание завершено</label><div class="pager"><button class="prev" data-go="${mi===0?"start":`m${mi}`}">← Назад</button><button class="next" data-go="${next}">${next==="final"?"К итогам →":"Следующий модуль →"}</button></div></div></section>`}
function materialsHtml(m,mi){const pack=window.WORKBOOK_MATERIALS&&window.WORKBOOK_MATERIALS[course.id]&&window.WORKBOOK_MATERIALS[course.id][mi];if(!pack)return `<div class="material-box"><b>Материалы курса</b><ul>${m.materials.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`;const rows=(items,key)=>items.map(item=>{const download=`${apiBase}/api/v1/materials/${key}/download?filename=${encodeURIComponent(item[1])}`;return `<li class="resource-item"><a class="resource-title" href="${esc(pack.folderUrl)}" target="_blank" rel="noopener" title="Открыть папку с инструкцией">${esc(item[0])}</a><a class="resource-download" href="${esc(download)}" title="Скачать файл">Скачать ↓</a></li>`}).join("");const sopKey=pack.sopFolderKey||"sop",sopUrl=pack.sopFolderUrl||window.WORKBOOK_MATERIALS.sopFolderUrl;return `<div class="material-box linked-materials"><div class="resource-heading"><div><b>Инструкции и СОПы</b><span>${esc(pack.label)}</span></div><a href="${esc(pack.folderUrl)}" target="_blank" rel="noopener">Открыть все материалы ↗</a></div><ul class="resource-list">${rows(pack.items,pack.folderKey)}</ul>${pack.sops&&pack.sops.length?`<details class="sop-list"><summary>СОПы по теме · ${pack.sops.length}</summary><ul class="resource-list">${rows(pack.sops,sopKey)}</ul><a class="all-sops" href="${esc(sopUrl)}" target="_blank" rel="noopener">Все СОПы на Яндекс Диске ↗</a></details>`:""}</div>`}
function quizHtml(m,mi){return `<section class="quiz"><div class="quiz-head"><div><div class="block-label">Проверьте себя</div><h2>Контрольные вопросы</h2></div><span>${m.quiz.length} вопроса · +10 очков за верный</span></div>${m.quiz.map((q,qi)=>questionHtml(q,mi,qi)).join("")}</section>`}
function questionHtml(q,mi,qi){const k=`${mi}-${qi}`,selected=state.answers[k];return `<fieldset class="question" data-question="${k}"><legend>${qi+1}. ${esc(q.text)}</legend>${q.options.map((o,oi)=>`<label class="option ${selected!==undefined&&oi===q.correct?"correct":""} ${selected!==undefined&&Number(selected)===oi&&oi!==q.correct?"wrong":""}"><input type="radio" name="q-${k}" value="${oi}" data-answer="${k}" ${Number(selected)===oi?"checked":""}><span>${esc(o)}</span></label>`).join("")}${selected===undefined?"":`<div class="feedback ${Number(selected)===q.correct?"good":""}"><b>${Number(selected)===q.correct?"Верно.":"Нужно уточнить."}</b> ${esc(q.explanation)}</div>`}</fieldset>`}
function finalHtml(){const s=stats();return `<section class="screen" id="final">${hero("✓","Финал","Ваш результат","Прогресс, темы для повторения и итоговая памятка по курсу.")}<div class="content"><div class="stats"><div class="stat"><b id="points">${s.points}</b><span>очков набрано</span></div><div class="stat"><b id="percent">${s.percent}%</b><span>общий прогресс</span></div><div class="stat"><b id="steps">${s.checked}/${s.totalChecks}</b><span>шагов практики</span></div></div><div class="review"><div class="block-label">Что стоит повторить</div><ul id="reviewList">${reviewList()}</ul></div><h2>Ваши записи</h2><div class="note-summary" id="notes">${notesHtml()}</div><h2>Итоговая карточка</h2><p>ФИО заполнено из данных входа. При необходимости добавьте должность или подразделение.</p><div class="certificate-form"><input id="certName" value="${esc(auth&&auth.full_name||state.profile.name||"")}" readonly><input id="certUnit" value="${esc(state.profile.unit||"")}" placeholder="Должность или подразделение"><button id="buildCert">Собрать карточку</button></div><div class="certificate" id="certificate"><img src="../assets/ifcm-logo.svg" alt="iFCM GROUP"><div class="block-label">Рабочая тетрадь завершена</div><h3>${esc(course.title)}</h3><div class="cert-name" id="certNameOut"></div><p id="certUnitOut"></p><p><b id="certResult">${s.percent}% программы · ${s.correct}/${s.totalQ} верных ответов</b></p></div><h2>Памятка</h2><div class="do-dont"><div><b>ДЕЛАЙТЕ ТАК</b><ul>${course.rules.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><b>НЕ ДЕЛАЙТЕ ТАК</b><ul>${course.critical.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div><div class="pager"><button class="prev" data-go="m${course.modules.length}">← Назад</button><button class="next" data-go="start">В начало ↑</button></div></div></section>`}
function reviewList(){return course.modules.map((m,mi)=>{let c=0;m.quiz.forEach((q,qi)=>{if(Number(state.answers[`${mi}-${qi}`])===q.correct)c++});return `<li><b>${esc(m.short)}</b> — верно ${c} из ${m.quiz.length}</li>`}).join("")}
function notesHtml(){const n=course.modules.map((m,i)=>({t:m.short,n:(state.notes[i]||"").trim()})).filter(x=>x.n);return n.length?n.map(x=>`<article><b>${esc(x.t)}</b><p>${esc(x.n).replaceAll("\n","<br>")}</p></article>`).join(""):`<p>Записи появятся здесь после заполнения полей в модулях.</p>`}
function show(id){if(!document.getElementById(id))id="start";document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===id));window.scrollTo({top:0,behavior:"smooth"})}
function update(){const s=stats();const rail=document.getElementById("rail");if(rail)rail.style.width=`${s.percent}%`;const top=document.getElementById("topScore");if(top)top.textContent=s.points;["points","percent","steps"].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=id==="points"?s.points:id==="percent"?`${s.percent}%`:`${s.checked}/${s.totalChecks}`});course.modules.forEach((_,i)=>{const e=document.querySelector(`[data-nav="m${i+1}"]`);if(e)e.classList.toggle("done",!!state.done[i])});const r=document.getElementById("reviewList");if(r)r.innerHTML=reviewList();const n=document.getElementById("notes");if(n)n.innerHTML=notesHtml();const cr=document.getElementById("certResult");if(cr)cr.textContent=`${s.percent}% программы · ${s.correct}/${s.totalQ} верных ответов`}
function refreshQuestion(k){const [mi,qi]=k.split("-").map(Number),old=document.querySelector(`[data-question="${k}"]`),wrap=document.createElement("div");if(!old)return;wrap.innerHTML=questionHtml(course.modules[mi].quiz[qi],mi,qi);old.replaceWith(wrap.firstElementChild)}
function exportText(){const s=stats(),rows=[course.title,`ФИО: ${auth&&auth.full_name||""}`,`Дата: ${new Date().toLocaleString("ru-RU")}`,`Прогресс: ${s.percent}%`,`Верных ответов: ${s.correct}/${s.totalQ}`,""];course.modules.forEach((m,i)=>rows.push(`${i+1}. ${m.short}`,state.notes[i]||"—",""));const blob=new Blob([rows.join("\n")],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${course.id}-v2-results.txt`;a.click();URL.revokeObjectURL(url)}
function wire(){document.addEventListener("change",onChange);document.addEventListener("input",onInput);document.addEventListener("click",onClick);window.addEventListener("hashchange",onHash);document.getElementById("print").onclick=()=>window.print();document.getElementById("export").onclick=exportText;document.getElementById("logout").onclick=()=>{writeSession(null);location.reload()};document.getElementById("reset").onclick=restartCourse;document.getElementById("buildCert").onclick=()=>{state.profile.name=auth&&auth.full_name||"";state.profile.unit=document.getElementById("certUnit").value.trim();save();document.getElementById("certNameOut").textContent=state.profile.name||"Участник курса";document.getElementById("certUnitOut").textContent=state.profile.unit;document.getElementById("certificate").classList.add("show")}}
async function restartCourse(){if(!confirm("Начать новую попытку? Текущие результаты сохранятся в истории администратора."))return;const button=document.getElementById("reset");button.disabled=true;try{await api(`/api/v1/progress/${course.id}/restart`,{method:"POST"});state=empty();localStorage.setItem(key,JSON.stringify(state));location.hash="start";location.reload()}catch(error){button.disabled=false;if(error.status===401){writeSession(null);renderLogin("Сеанс завершён. Войдите повторно");return}notify(error.message,true)}}
function onChange(e){if(e.target.matches("[data-check]")){state.checks[e.target.dataset.check]=e.target.checked;save()}if(e.target.matches("[data-done]")){state.done[e.target.dataset.done]=e.target.checked;save()}if(e.target.matches("[data-answer]")){state.answers[e.target.dataset.answer]=Number(e.target.value);save();refreshQuestion(e.target.dataset.answer)}}
function onInput(e){if(e.target.matches("[data-note]")){state.notes[e.target.dataset.note]=e.target.value;save()}}
function onClick(e){const b=e.target.closest("[data-go]");if(b)location.hash=b.dataset.go}
function onHash(){show(location.hash.slice(1))}
if(!apiBase){renderLogin("Сервис сохранения ещё не подключён к серверу")}else if(auth&&auth.token){openWorkbook()}else{renderLogin()}
})();
