/* Reusable accessible game controls for the editor preview and all workbooks. */
window.LearningGames = (() => {
 const bindings=new WeakMap();
 const types={sequence:'Собери последовательность',sort:'Распредели по категориям',match:'Подбери пару',errors:'Найди ошибку',scenario:'Разбери ситуацию',documents:'Собери комплект документов',hotspots:'Найди на экране'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function initial(b){return {values:b.type==='sequence'?b.items.map((_,i)=>i).reverse():b.type==='sort'||b.type==='match'?b.items.map(()=>-1):[],submitted:false}}
 function body(b,a){const values=a.values||[];
  if(b.type==='sequence')return `<ol class="game-order">${values.map((v,i)=>`<li><span>${esc(b.items[v])}</span><div><button type="button" data-move="${i}" data-dir="-1" ${i===0?'disabled':''} aria-label="Поднять карточку ${esc(b.items[v])}">↑</button><button type="button" data-move="${i}" data-dir="1" ${i===values.length-1?'disabled':''} aria-label="Опустить карточку ${esc(b.items[v])}">↓</button></div></li>`).join('')}</ol>`;
  if(b.type==='sort'||b.type==='match')return `<div class="game-pairs">${b.items.map((text,i)=>`<label><span>${esc(text)}</span><select data-pair="${i}" aria-label="Ответ для ${esc(text)}"><option value="-1">Выберите…</option>${b.targets.map((_,j)=>{const k=(j+1)%b.targets.length;return `<option value="${k}" ${values[i]===k?'selected':''}>${esc(b.targets[k])}</option>`}).join('')}</select></label>`).join('')}</div>`;
  if(b.type==='scenario'){let si=0,out='';for(let n=0;si!==-1&&n<b.steps.length;n++){const s=b.steps[si],choice=values[n];out+=`<fieldset class="game-step"><legend>${esc(s.text)}</legend>${s.options.map((o,i)=>`<label><input type="radio" name="game-${b.id}-${n}" data-step="${n}" data-step-index="${si}" value="${i}" ${choice===i?'checked':''}>${esc(o.text)}</label>`).join('')}${choice!==undefined?`<p class="game-consequence">${esc(s.options[choice]?.consequence||'')}</p>`:''}</fieldset>`;if(choice===undefined)break;si=s.options[choice]?.next??-1}return out}
  const choices=`<div class="game-choices">${b.items.map((text,i)=>`<label><input type="checkbox" data-choice="${i}" ${values.includes(i)?'checked':''}>${esc(text)}</label>`).join('')}</div>`;
  if(b.type==='hotspots')return `<p class="game-help">Выберите области на изображении или отметьте их в списке ниже.</p><div class="game-screen"><img src="${esc(b.image)}" alt="${esc(b.title||'Учебный экран')}">${b.regions.map((r,i)=>`<button type="button" class="game-region ${values.includes(i)?'selected':''}" data-region="${i}" aria-pressed="${values.includes(i)}" aria-label="${esc(b.items[i])}" style="left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%">${i+1}</button>`).join('')}</div>`+choices;
  return choices;
 }
 function html(b,a=initial(b)){return `<article class="learning-game" data-game="${esc(b.id)}"><div class="game-kicker">Мини-игра · ${esc(types[b.type])} · ${b.points??10} баллов</div><h3>${esc(b.title||types[b.type])}</h3><p class="game-text">${esc(b.text)}</p>${body(b,a)}${b.hint?`<details class="game-hint"><summary>Подсказка</summary><p>${esc(b.hint)}</p></details>`:''}<div class="game-actions"><button type="button" data-submit-game>Проверить решение</button><button type="button" data-reset-game>Начать игру заново</button></div><div class="game-feedback" role="status">${a.submitted?'Решение сохранено. Нажмите «Проверить решение», чтобы увидеть оценку.':''}</div></article>`}
 function complete(b,a){if(b.type==='sequence')return true;if(['sort','match'].includes(b.type))return a.values.length===b.items.length&&a.values.every(x=>x>=0)&& (b.type!=='match'||new Set(a.values).size===a.values.length);if(b.type==='scenario'){let si=0;for(const v of a.values){if(si===-1)return false;si=b.steps[si]?.options[v]?.next??-1}return si===-1}return true}
 function bind(root,blocks,state,onChange,grade){
  bindings.get(root)?.abort();const controller=new AbortController();bindings.set(root,controller);
  const map=new Map(blocks.map(b=>[b.id,b]));let busy=new Set();
  function locate(t){const card=t.closest('[data-game]');if(!card)return {};const b=map.get(card.dataset.game);if(!b)return {};return {card,b,a:state.answers[b.id]||initial(b)}}
  function redraw(card,b,a){const focus=document.activeElement?.getAttribute('data-pair');card.outerHTML=html(b,a);if(focus!==null&&focus!==undefined)root.querySelector(`[data-game="${b.id}"] [data-pair="${focus}"]`)?.focus()}
  function changed(card,b,a){a.submitted=false;state.answers[b.id]=a;onChange(b,a);redraw(card,b,a)}
  root.addEventListener('change',ev=>{const {card,b,a}=locate(ev.target);if(!b)return;const t=ev.target;if(t.hasAttribute('data-pair'))a.values[Number(t.dataset.pair)]=Number(t.value);else if(t.hasAttribute('data-choice')){const v=Number(t.dataset.choice);a.values=t.checked?[...new Set([...a.values,v])]:a.values.filter(x=>x!==v)}else if(t.hasAttribute('data-step')){const n=Number(t.dataset.step);a.values=a.values.slice(0,n);a.values.push(Number(t.value))}else return;changed(card,b,a)},{signal:controller.signal});
  root.addEventListener('click',async ev=>{const t=ev.target.closest('button');if(!t)return;const {card,b,a}=locate(t);if(!b)return;
   if(t.hasAttribute('data-move')){const i=Number(t.dataset.move),j=i+Number(t.dataset.dir);if(j<0||j>=a.values.length)return;[a.values[i],a.values[j]]=[a.values[j],a.values[i]];changed(card,b,a)}
   else if(t.hasAttribute('data-region')){const i=Number(t.dataset.region);a.values=a.values.includes(i)?a.values.filter(x=>x!==i):[...a.values,i];changed(card,b,a)}
   else if(t.hasAttribute('data-reset-game'))changed(card,b,initial(b));
   else if(t.hasAttribute('data-submit-game')){if(busy.has(b.id))return;const box=card.querySelector('.game-feedback');if(!complete(b,a)){box.textContent='Заполните все соответствия или завершите ситуацию.';return}busy.add(b.id);t.disabled=true;try{a.submitted=true;state.answers[b.id]=a;const snapshot=structuredClone(a),result=await grade(b,snapshot);if(JSON.stringify(state.answers[b.id])!==JSON.stringify(snapshot))return;state.answers[b.id]=a;await onChange(b,a);const target=root.querySelector(`[data-game="${b.id}"] .game-feedback`);if(target){target.textContent=(result.correct?'Верно! ':'Есть ошибки. ')+(result.manual?'Ответ ожидает проверки преподавателем.':`${result.points} баллов. `)+(result.explanation||'');target.classList.toggle('good',!!result.correct)}}catch(x){a.submitted=false;box.textContent=x.message||'Не удалось проверить решение'}finally{busy.delete(b.id);t.disabled=false}}
  },{signal:controller.signal});
 }
 function answerText(b,a){if(!a||!Array.isArray(a.values))return 'Нет ответа';if(b.type==='scenario'){let si=0;return a.values.map(v=>{if(si===-1)return '';const s=b.steps[si],o=s?.options[v];si=o?.next??-1;return (s?.text||'')+' → '+(o?.text||'')}).join('\n')}if(['sort','match'].includes(b.type))return b.items.map((x,i)=>x+' → '+(b.targets[a.values[i]]||'Не выбрано')).join('\n');return a.values.map(i=>b.items[i]||'').join('\n')}
 function previewGrade(b,a){let right=false;if(b.type==='scenario'){let si=0;right=true;for(const v of a.values){if(si===-1){right=false;break}const s=b.steps[si];right=right&&v===s.correct;si=s.options[v]?.next??-1}right=right&&si===-1}else{const selected=['sequence','sort','match'].includes(b.type)?a.values:[...a.values].sort((x,y)=>x-y),expected=['sequence','sort','match'].includes(b.type)?b.correct:[...b.correct].sort((x,y)=>x-y);right=JSON.stringify(selected)===JSON.stringify(expected)}return {correct:right,points:right?(b.points??10):0,explanation:b.explanation||''}}
 return {types,initial,html,bind,answerText,previewGrade};
})();
