(async()=>{
const root=document.getElementById('app'),params=new URLSearchParams(location.search),preview=params.has('preview'),cid=params.get('course'),e=WB.esc;
let content,state={answers:{},checks:{},notes:{},done:{},evidence:{}},auth=JSON.parse(sessionStorage.getItem('builder-student-session')||'null'),timer,saving=null,dirty=false,urls=[];
async function api(path,body,method='GET'){const r=await fetch('/api/v1/'+path,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth.token}:{})},...(body?{body:JSON.stringify(body)}:{})});const p=await r.json();if(!r.ok)throw Error(typeof p.detail==='string'?p.detail:'Не удалось выполнить запрос');return p}
function msg(t){document.getElementById('status').textContent=t}
function login(){root.innerHTML=`<main class="login card"><img src="../assets/ifcm-logo.svg" width="120" alt="IFCM"><h1>${e(content.title)}</h1><form id="login"><label>Фамилия и имя<input name="full_name" autocomplete="name" required></label><label>Код доступа<input name="code" type="password" required></label><button>Открыть тетрадь</button><div id="status" role="status"></div></form></main>`;document.getElementById('login').onsubmit=async ev=>{ev.preventDefault();try{auth=await api('session',{full_name:ev.target.elements.namedItem("full_name").value,code:ev.target.elements.namedItem("code").value,course_id:cid},'POST');sessionStorage.setItem('builder-student-session',JSON.stringify(auth));await open()}catch(x){msg(x.message)}}}
async function open(){if(!preview){const p=await api('progress/'+cid);state={...state,...(p.state||{}),evidence:p.state?.evidence||{}}}draw()}
function draw(){urls.forEach(URL.revokeObjectURL);urls=[];root.innerHTML=`${preview?'<div class="preview-banner">Предпросмотр: ответы и скриншоты здесь не сохраняются на сервере. <a href="index.html">Вернуться к редактору</a></div>':''}<header><img src="../assets/ifcm-logo.svg" alt="IFCM"><a href="../v3/index.html">Каталог</a><span>${e(auth?.full_name||'Предпросмотр')}</span><span id="status" class="status" role="status"></span>${preview?'':'<button id="save">Сохранить</button><button id="restart" class="secondary">Начать заново</button><button id="logout" class="secondary">Выйти</button>'}</header><main class="layout"><aside class="card section-nav">${content.sections.map((s,i)=>`<a href="#section-${i}">${i+1}. ${e(s.title)}</a>`).join('')}</aside><div>${WB.content(content,state)}<div id="result" class="result">Результаты появятся после сохранения</div></div></main>`;if(!preview){document.getElementById('save').onclick=save;document.getElementById('logout').onclick=async()=>{await save();if(dirty)return;sessionStorage.removeItem('builder-student-session');auth=null;login()};document.getElementById('restart').onclick=async()=>{if(!confirm('Начать новую попытку? Ответы и скриншоты текущей попытки останутся в истории.'))return;await save();if(dirty)return;await api('progress/'+cid+'/restart',{},'POST');state={answers:{},checks:{},notes:{},done:{},evidence:{}};draw()};for(const b of content.sections.flatMap(s=>s.blocks).filter(b=>b.type==='practice'))gallery(b.id);api('progress/'+cid).then(p=>result(p.summary));feedback()}}
function result(s){if(s)document.getElementById('result').textContent=`Прогресс: ${s.percent}% · Баллы: ${s.points} · Верных ответов: ${s.correct}/${s.totalQ}. Ожидают проверки: ${s.pendingReview||0}. Открытые ответы автоматически не оцениваются.`}
async function save(){
 if(preview)return;clearTimeout(timer);
 if(saving){await saving;if(dirty)await save();return}
 const snapshot=structuredClone(state);dirty=false;let success=false;
 saving=(async()=>{msg('Сохраняем…');try{const p=await api('progress/'+cid,{state:snapshot,summary:{}},'PUT');msg('Сохранено');result(p.summary);await feedback();success=true}catch(x){msg(x.message+' — изменения пока не сохранены');dirty=true}})();
 await saving;saving=null;
 if(dirty&&success)await save();
}
async function feedback(){const items=await api('workbooks/'+cid+'/feedback');root.querySelectorAll('.teacher-feedback').forEach(x=>x.remove());for(const [bid,r] of Object.entries(items)){const anchor=root.querySelector(`[data-check="${bid}"], [data-open="${bid}"], [data-answer="${bid}"]`);if(anchor){const p=document.createElement('p');p.className='teacher-feedback';p.textContent=`Преподаватель: ${r.checked?'проверено':'ожидает проверки'} · ${r.points} баллов. ${r.comment}`;anchor.closest('.block').append(p)}}}
function change(){if(preview)return;dirty=true;clearTimeout(timer);timer=setTimeout(save,900)}
root.addEventListener('change',async ev=>{const t=ev.target;if(t.dataset.answer){const b=content.sections.flatMap(s=>s.blocks).find(b=>b.id===t.dataset.answer),i=Number(t.value);state.answers[b.id]=b.type==='multiple'?(t.checked?[...new Set([...(state.answers[b.id]||[]),i])]:(state.answers[b.id]||[]).filter(x=>x!==i)):[i];change()}if(t.dataset.check){state.checks[t.dataset.check]=t.checked;change()}if(t.dataset.done!==undefined){state.done[t.dataset.done]=t.checked;change()}if(t.dataset.evidence){if(preview){msg('Загрузка скриншотов доступна в опубликованной тетради');return}const bid=t.dataset.evidence,b=content.sections.flatMap(s=>s.blocks).find(b=>b.id===bid),files=[...t.files];try{if(files.length+(state.evidence[bid]||[]).length>(b.maxImages||3))throw Error('Превышено количество скриншотов');for(const f of files){if(f.size>5000000)throw Error('Скриншот: не более 5 МБ');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(f)});const p=await api(`workbooks/${cid}/evidence/${bid}`,{data},'POST');(state.evidence[bid]??=[]).push(p.id)}await gallery(bid);await save()}catch(x){msg(x.message)}t.value=''}});
root.addEventListener('input',ev=>{const t=ev.target;if(t.dataset.open){state.answers[t.dataset.open]=t.value;change()}if(t.dataset.note){state.notes[t.dataset.note]=t.value;change()}});
async function gallery(bid){const target=root.querySelector(`[data-gallery="${bid}"]`);if(!target)return;target.innerHTML='';for(const iid of state.evidence[bid]||[]){const r=await fetch('/api/v1/builder/evidence/'+iid,{headers:{Authorization:'Bearer '+auth.token}});if(!r.ok){msg('Не удалось открыть скриншот');continue}const url=URL.createObjectURL(await r.blob());urls.push(url);const div=document.createElement('div'),img=document.createElement('img'),btn=document.createElement('button');img.src=url;img.alt='Скриншот задания';img.className='workbook-image';img.style.maxWidth='350px';btn.textContent='Убрать скриншот';btn.className='secondary';btn.onclick=async()=>{state.evidence[bid]=state.evidence[bid].filter(x=>x!==iid);await gallery(bid);change()};div.append(img,btn);target.append(div)}}
window.addEventListener('beforeunload',ev=>{if(dirty||saving){ev.preventDefault();ev.returnValue=''}});
try{if(preview){content=JSON.parse(sessionStorage.getItem('builder-preview'));if(!content)throw Error('Откройте предпросмотр из конструктора');draw()}else{content=(await api('workbooks/'+cid)).content;if(auth)await open();else login()}}catch(x){root.innerHTML=`<main class="card"><h1>Не удалось открыть тетрадь</h1><p>${e(x.message)}</p><a href="index.html">Конструктор</a></main>`}
})();
